"""
Quote retrieval — unified flow for all themes.

Each run randomly picks a mode:
  - real_author   : Gemini finds a real quote by a known person (non-obvious sources preferred)
  - social_viral  : Gemini finds/writes a quote in the style of viral social media posts
  - llm_generated : Gemini writes an original quote (short and concrete encouraged)

All quotes pass through a quality gate before acceptance.
Fallback: curated pool in config/curated_quotes.yml.

Returns: {text, author, highlight, source}
  source: "gemini_real" | "gemini_original" | "curated" | "fallback"
"""
import hashlib
import logging
import os
import random
import re
import time
from pathlib import Path

import yaml

logger = logging.getLogger(__name__)

MAX_ATTEMPTS       = 2   # 5 candidates per call — usually enough on attempt 1
N_CANDIDATES       = 5   # bigger pool to give the judge a real choice
IMAGE_JUDGE_MAX    = 3   # kept in image_judge.py — noted here for clarity
MIN_QUALITY_SCORE  = 7
MIN_UNIQUENESS     = 7   # raised from 6 — higher bar to clear on repeat/clichéd content
RETRY_DELAY        = 2


# ---------------------------------------------------------------------------
# Load curated fallback pool
# ---------------------------------------------------------------------------

def _load_curated() -> dict[str, list[dict]]:
    path = Path(__file__).parent.parent / "config" / "curated_quotes.yml"
    if not path.exists():
        return {}
    with path.open(encoding="utf-8") as f:
        data = yaml.safe_load(f) or {}
    return data.get("quotes", {})

_CURATED_POOL = _load_curated()


# ---------------------------------------------------------------------------
# Prompt builders
# ---------------------------------------------------------------------------

# ---------------------------------------------------------------------------
# Hook-first patterns — the structural forms that drive save/share on Indian
# emotional-wisdom pages. The quote generator is biased toward these because
# a flat observation scrolls by; a pattern-interrupt opener stops thumbs.
# ---------------------------------------------------------------------------

_HOOK_PATTERNS_GUIDE = """\
STRUCTURE — at least 2 of the 3 candidates should open with a
pattern-interrupt / second-person hook. These forms consistently drive
saves and shares in this niche:

  - "Nobody tells you that..."           (hidden truth)
  - "One day you'll realise..."          (delayed recognition)
  - "The hardest part isn't X. It's Y."  (expectation subversion)
  - "You won't know X until Y."          (earned wisdom)
  - "It's not that X — it's that Y."     (correction)
  - "There's a difference between X and Y." (precision)
  - A single declarative sentence that lands like a confession — no
    build-up, no "Life is...", no "We all..."

AVOID flat openers that sound like advice ("You should...", "Be the..."),
generic truisms ("Life is beautiful", "Love yourself"), or performed
wisdom ("In the garden of the soul..."). If it sounds like a Pinterest
caption a boomer would share, do not write it.
"""


# These examples set the QUALITY BAR the model should match. They are not
# generated by the model and not posted — they are the benchmark.
# Each one has the four properties a save-worthy quote needs:
#   1. Specific concrete detail (object, place, time, action, relationship)
#   2. Unexpected second half — a twist or subverted expectation
#   3. Strong claim, no hedging ("some of us"), no abstract nouns
#   4. Short enough to screenshot — usually 10-20 words
# Drawn from a wide pool of Indian-life touchpoints so the model doesn't
# pattern-match onto the same 2-3 nouns.
_SAVE_WORTHY_EXAMPLES = """\
QUALITY BAR — these are killer lines, the kind that get screenshotted
and forwarded on WhatsApp. Mediocre is "some habits outlive feelings."
Killer is anchored, surprising, and feels like an overheard confession.
DO NOT copy these — match their sharpness while drawing from your own
specifics.

  - "Parents don't age with you. They age silently while you're busy
    becoming someone."
  - "Your therapist isn't your friend. That's why it works."
  - "Mom still knocks before entering. That's how I learnt respect
    isn't loud."
  - "The version of you they rejected ended up saving someone else."
  - "You miss who they were, not who they are."
  - "You don't owe your younger self loyalty to their dreams."
  - "Some people cry in the bathroom. Some in traffic. Some in group
    chats. Everybody's got a spot."
  - "Half my prayers are just thank-yous I forgot to send to people."
  - "You will spend years training for an interview that lasted nine
    minutes and changed nothing."
  - "The wedding photos don't show the part where she went to the
    bathroom and didn't cry — she was past that."
  - "Your father's WhatsApp 'good morning' images are how he says he's
    still here, just quieter."
  - "Some friendships end in a fight. Most end in a left-on-seen."
  - "The siblings who fought over the last paratha grow up to text
    each other 'eat properly'."
  - "There's a Diwali photograph somewhere where everyone in it is now
    in a different city."
  - "The day you start choosing the silence over the explanation, you've
    grown up — and lost something."
  - "Hostel roommates know things about you your wife never will."

NOTICE: every example uses a DIFFERENT specific anchor — parents,
therapist, knock, prayer, interview, wedding, WhatsApp, friendships,
paratha, Diwali, silence, hostel. Variety is the point. The model
should pull from a wide vocabulary of Indian-life specifics, not the
same 2-3 nouns every post.
"""


# Hard bans plus content-balance rules that prevent the model from
# pattern-matching onto a small set of "easy" Indian-noun crutches.
_BANNED_STRUCTURES = """\
HARD BANS — a quote containing ANY of these is automatically rejected:
  - Weak hedges: "some of us", "sometimes", "maybe", "perhaps",
    "in a way", "somehow", "a little", "a bit"
  - Abstract-noun clichés: "healing", "energy", "vibes", "journey",
    "warrior", "storm", "chapter", "rollercoaster", "phase", "bloom"
  - Hollow verbs: "thrive", "glow up", "manifest", "align", "elevate"
  - Empty structures: "Life is...", "We all...", "Everyone has...",
    "At the end of the day...", "In the end..."
  - Generic advice: "be yourself", "chase your dreams", "live your
    truth", "trust the process", "one day at a time"
  - Brand-name spiritual: "the universe", "divine timing", "higher self"

NOUN-CRUTCH RULE — you may use these words but only sparingly:
"chai", "auto", "auto-rickshaw", "rickshaw", "beta", "uncle", "aunty".
Across your 3 candidates, AT MOST ONE may use any of these tokens.
Reach instead for: phone, screen-time, last-seen, double-tick, drawer,
wardrobe, hostel, mess, train, platform, station, shaadi, mehendi,
sangeet, Diwali, Holi, board exam, viva, interview, internship,
landlord, PG, EMI, salary, group chat, voice note, missed call,
ringtone, photo album, SIM, courier, parcel, watchman, society,
kirana, dabba, tiffin, lunch break, bus, metro, Uber, Ola, scooter,
mom's call, dad's silence, dadi, nani, chacha, mausi, cousin, brother,
sister, school bag, bunk, classroom, college bench, library, exam
hall, viva, hostel mess, balcony, terrace, monsoon, evening walk,
festival, sweets, rangoli, anniversary, engagement, alimony — pick
DIFFERENT specifics for each candidate.

KILLER NOT MEDIOCRE — re-read your candidate. If it could appear on
any generic Pinterest board, it is mediocre. If it makes you go "oh
that's specific to my life" within 2 seconds, it is killer. Reject
mediocre yourself before scoring.
"""


_CLICHE_MAP = {
    "morning":     '"believe in yourself", "chase your dreams", "rise and shine", "hustle hard", "surviving", "warrior", "every day is a gift"',
    "wisdom":      '"everything happens for a reason", "be the change", "time heals all wounds", "your journey", "best version of yourself", "broken into pieces"',
    "love":        '"soulmates", "love conquers all", "you complete me", "you deserve better", "red flags"',
    "mindfulness": '"be present", "let it go", "inner peace", "heal yourself", "your healing journey"',
    "goodnight":   '"count your blessings", "tomorrow is a new day", "sweet dreams", "you survived today"',
    "latenight":   '"time heals", "let go and move on", "you deserve better", "surviving", "healing is not linear", "warrior"',
    "womenpower":  '"boss babe", "girl boss", "she believed she could", "women are strong", "girl power", "empowered women empower women", "know your worth", "her vibe", "toxic", "healed", "healing journey", "unbothered"',
}


def _build_real_prompt(category: str, max_words: int, topic_block: str) -> str:
    cliches = _CLICHE_MAP.get(category, '"overused clichés"')
    bans    = _BANNED_STRUCTURES
    return f"""\
You are finding and evaluating real quotes for @_daily_dose_of_wisdom__, \
an Indian Instagram page for emotionally intelligent youth aged 18-35.

Find {N_CANDIDATES} DIFFERENT real quotes — each actually written or spoken by a known person. \
Prefer filmmakers, musicians, comedians, athletes, novelists, or contemporary thinkers \
over the usual Rumi / Stoics / Einstein pool — those are overexposed. A sharp line from \
a film, a lyric that works standalone, or a line from a novelist almost nobody quotes are all valid.

{topic_block}

{bans}

Rules for each quote:
- REAL quote by a REAL, named person — not "Unknown" or "Anonymous"
- Maximum {max_words} words total. Hard limit.
- Must resonate with an Indian aged 18-35 in 2025 — timeless but not cliché
- Must feel RARE — not one of the top 1000 most quoted lines on the internet
- No clichés: {cliches}
- Short is fine — a complete 6-word quote beats a padded 20-word one
- All {N_CANDIDATES} must be from different authors and different emotional angles

Score each on 4 dimensions (1-10): virality, engagement, uniqueness (1-4 if widely circulated), freshness.

DO NOT pre-pick the best — return ALL {N_CANDIDATES} so the judge can choose.
Return ONLY a valid JSON array — no markdown, no explanation:
[
  {{"quote":"PLAIN TEXT ONLY — the exact words. No quotation marks. No attribution suffix.","author":"Full Name",\
"virality":<1-10>,"engagement":<1-10>,"uniqueness":<1-10>,"freshness":<1-10>,"reason":"<one short sentence>"}},
  ... {N_CANDIDATES} items total
]
"""


def _build_social_prompt(category: str, max_words: int, topic_block: str) -> str:
    cliches   = _CLICHE_MAP.get(category, '"overused clichés"')
    hooks     = _HOOK_PATTERNS_GUIDE
    examples  = _SAVE_WORTHY_EXAMPLES
    bans      = _BANNED_STRUCTURES
    return f"""\
You are writing quotes in the style of things that go genuinely viral on social media \
for @_daily_dose_of_wisdom__, an Indian Instagram page for emotionally intelligent youth aged 18-35.

Think Reddit threads, Twitter/X posts, Tumblr, Pinterest, Instagram captions — the kind \
of line a real 25-year-old wrote from experience that thousands of people screenshot because \
they felt seen. Not profound philosophy. Not a motivational poster. Just one true thing said simply.

{topic_block}

{examples}

Write {N_CANDIDATES} DIFFERENT candidates. Each should feel like:
- Something a real person said, not a writer performing wisdom
- The kind of line you text a friend and they reply "damn"
- Simple enough that the visual does half the work — short is often better
- Warm and specific, not vague and grand

Each quote MUST contain a concrete, specific detail — an object, a place,
a time of day, a specific action, a named relationship, a sensory cue —
not only abstract feelings. Every candidate should have a twist or
unexpected pivot in its second half.

{hooks}

{bans}

Rules for each:
- Maximum {max_words} words. Short quotes (4-8 words) are especially welcome.
- Concrete over abstract — one precise feeling, not a life philosophy
- No clichés: {cliches}
- All {N_CANDIDATES} must explore different feelings or angles
- Author field must be "Original"

Score each on 4 dimensions (1-10): virality, engagement, uniqueness, freshness.

DO NOT pre-pick the best — return ALL {N_CANDIDATES} so the judge can choose.
Return ONLY a valid JSON array — no markdown, no explanation:
[
  {{"quote":"PLAIN TEXT ONLY — no quotation marks, no attribution, just the words.","author":"Original",\
"virality":<1-10>,"engagement":<1-10>,"uniqueness":<1-10>,"freshness":<1-10>,"reason":"<one short sentence>"}},
  ... {N_CANDIDATES} items total
]
"""


def _build_llm_prompt(category: str, max_words: int, topic_block: str) -> str:
    cliches  = _CLICHE_MAP.get(category, '"overused clichés"')
    hooks    = _HOOK_PATTERNS_GUIDE
    examples = _SAVE_WORTHY_EXAMPLES
    bans     = _BANNED_STRUCTURES
    return f"""\
You are writing original quotes for @_daily_dose_of_wisdom__, \
an Indian Instagram page for emotionally intelligent youth aged 18-35.

Write {N_CANDIDATES} DIFFERENT original quotes. Each should feel like something a thoughtful person \
said once and never repeated — not assembled from parts of other quotes. Specific and earned, not performed.

{topic_block}

{examples}

Each quote MUST contain a concrete, specific detail — an object, a place,
a time of day, a specific action, a named relationship, a sensory cue —
not only abstract feelings. Every candidate should have a twist or
unexpected pivot in its second half.

{hooks}

{bans}

Rules for each:
- ORIGINAL — not attributed to any real person
- Maximum {max_words} words total. Hard limit.
- Short is valid — if the feeling is complete in 5 words, stop at 5. Short quotes let the visual carry the post.
- Concrete over abstract: "you still made the tea on the worst morning" beats "strength lives in small moments"
- Must resonate with an Indian aged 18-30 at a gut level
- No Pinterest-assembled philosophy — warm simple lines are fine if they're genuinely fresh
- No clichés: {cliches}
- All {N_CANDIDATES} must be emotionally distinct from each other

Score each on 4 dimensions (1-10): virality, engagement, uniqueness, freshness.

DO NOT pre-pick the best — return ALL {N_CANDIDATES} so the judge can choose.
Return ONLY a valid JSON array — no markdown, no explanation:
[
  {{"quote":"PLAIN TEXT ONLY — no quotation marks, no attribution, just the words.","author":"Original",\
"virality":<1-10>,"engagement":<1-10>,"uniqueness":<1-10>,"freshness":<1-10>,"reason":"<one short sentence>"}},
  ... {N_CANDIDATES} items total
]
"""


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _hash(text: str) -> str:
    return hashlib.md5(text.lower().strip().encode()).hexdigest()[:16]


_QUOTE_CHARS = '\u201c\u201d\u2018\u2019\"\'\u00ab\u00bb\u201e\u201f'

def _clean_text(text: str) -> str:
    """Strip quotation marks and author attributions from quote text.

    Dashes INSIDE the quote (e.g. "self-doubt", "day — night") are preserved
    because the pattern only matches a trailing separator followed by a
    Capitalised Name with no further separators.
    """
    text = text.strip().strip(_QUOTE_CHARS).strip()
    # Strip trailing author attribution: separator + space + Capitalised Name
    # e.g. " - Krishnamurti", " — Rumi", " ~ Unknown", " – Osho"
    text = re.sub(r'\s*[-\u2014\u2013~]\s*[A-Z][^-\u2014\u2013~\n]{1,60}$', '', text).strip()
    text = text.strip(_QUOTE_CHARS).strip()
    return text


def _extract_highlight(text: str) -> str:
    parts = [p.strip() for p in re.split(r"[.!?—–]", text) if p.strip()]
    if len(parts) > 1:
        last = parts[-1]
        words = last.split()
        if 3 <= len(words) <= 6:
            return last
        if len(words) > 6:
            return " ".join(words[:5])
    words = text.split()
    if len(words) <= 6:
        return text
    return " ".join(words[-5:])


def _call(prompt: str) -> str:
    """Delegate to the provider cascade in src.llm."""
    from src.llm import generate_text
    return generate_text(prompt, role="quote_generation")


def _append_avoid_hint(prompt: str, recent_hints: list[str]) -> str:
    if not recent_hints:
        return prompt
    lines = "\n".join(f"- {h}…" for h in recent_hints[-20:])
    return prompt + f"\n\nAvoid quotes on the same theme or idea as these recent posts:\n{lines}\n"


def _parse_quote_json(raw: str) -> tuple[str, str] | None:
    import json
    m = re.search(r"\{.*\}", raw, re.DOTALL)
    if not m:
        return None
    try:
        data = json.loads(m.group())
        q = _clean_text(data.get("quote", ""))
        a = data.get("author", "").strip()
        if q and a:
            return q, a
    except Exception:
        pass
    return None


def _parse_candidates_array(raw: str) -> list[dict]:
    """Parse the JSON array of candidates returned by the generator prompts."""
    import json
    m = re.search(r"\[.*\]", raw, re.DOTALL)
    if not m:
        return []
    try:
        arr = json.loads(m.group())
        return arr if isinstance(arr, list) else []
    except Exception:
        return []


# ---------------------------------------------------------------------------
# Quote judge — separate LLM pass that picks the best from N candidates.
# Self-scored generation is too lenient on its own output; an outside
# judge step is more rigorous.
# ---------------------------------------------------------------------------

_JUDGE_PROMPT = """\
You are picking the SINGLE best quote to post on @_daily_dose_of_wisdom__,
an Indian Instagram page for emotionally intelligent youth aged 18-35.

Candidates:
{numbered}

Quality bar — pick the one that:
  1. Has a specific concrete noun (object, place, relationship, scene)
  2. Has an unexpected pivot or twist in its second half
  3. Makes a strong claim — no hedging like "some of us", "sometimes"
  4. Feels like an overheard confession, not performed wisdom
  5. Would make a real Indian 18-35 say "oh that's exactly..." in 2 seconds

Penalise: candidates that overuse {{chai, auto, rickshaw, beta, uncle, aunty}}
when other candidates have richer specific anchors. The page should not feel
like every post is about the same 3 nouns — prefer variety.

Penalise: anything that sounds like Pinterest, motivation poster, or
generic life advice. Reject performed wisdom in favour of lived truth.

Return ONLY valid JSON — no markdown, no extra text:
{{"pick": <1-based index>, "reason": "<one short sentence why this beat the others>"}}
"""


def _judge_candidates(candidates: list[dict]) -> dict | None:
    """Pick the most save-worthy candidate via a separate LLM call.
    Falls back to highest self-scored on judge failure."""
    if not candidates:
        return None
    if len(candidates) == 1:
        return candidates[0]

    numbered = "\n".join(
        f"  {i+1}. \"{c.get('text', '')}\" — {c.get('author', 'Original')}"
        for i, c in enumerate(candidates)
    )
    prompt = _JUDGE_PROMPT.format(numbered=numbered)

    try:
        from src.llm import generate_text
        raw = generate_text(prompt, role="quote_judge")
        m = re.search(r"\{.*\}", raw, re.DOTALL)
        if m:
            import json as _json
            data = _json.loads(m.group())
            pick = int(data.get("pick", 0))
            reason = data.get("reason", "")
            if 1 <= pick <= len(candidates):
                logger.info(f"  Judge picked #{pick}: {reason}")
                return candidates[pick - 1]
    except Exception as exc:
        logger.warning(f"  Quote judge failed ({exc}) — falling back to highest self-score")

    # Fallback: highest self-scored candidate
    return max(candidates, key=lambda c: c.get("score", 0))


# ---------------------------------------------------------------------------
# Curated fallback
# ---------------------------------------------------------------------------

def _pick_curated(category: str, posted_hashes: set) -> dict | None:
    pool = _CURATED_POOL.get(category, [])
    if not pool:
        return None
    available = [q for q in pool if _hash(q["text"]) not in posted_hashes]
    if not available:
        available = pool
    item = dict(random.choice(available))
    item.setdefault("highlight", _extract_highlight(item["text"]))
    item["source"] = "curated"
    return item


# ---------------------------------------------------------------------------
# Core generation — unified flow for all themes
# ---------------------------------------------------------------------------

def _generate_with_validation(
    theme: str,
    posted_hashes: set,
    recent_hints: list[str] | None = None,
) -> dict | None:
    from src.content_config import get_max_words, get_topic_info

    max_words   = get_max_words(theme)
    info        = get_topic_info(theme)
    topic_block = info["topic_block"]
    image_hint  = info["image_hint"]

    # womenpower: original voice only — real attribution breaks the personal tone
    _modes = ["social_viral", "llm_generated"] if theme == "womenpower" else ["real_author", "social_viral", "llm_generated"]
    mode = random.choice(_modes)
    logger.info(f"  Mode: {mode}")

    if mode == "real_author":
        base_prompt = _build_real_prompt(theme, max_words, topic_block)
    elif mode == "social_viral":
        base_prompt = _build_social_prompt(theme, max_words, topic_block)
    else:
        base_prompt = _build_llm_prompt(theme, max_words, topic_block)
    prompt = _append_avoid_hint(base_prompt, recent_hints or [])

    source_name = ("gemini_real" if mode == "real_author"
                   else "gemini_social" if mode == "social_viral"
                   else "gemini_original")

    fallback: dict | None = None  # best below-bar candidate, kept across attempts

    for attempt in range(1, MAX_ATTEMPTS + 1):
        logger.info(f"  Quote attempt {attempt}/{MAX_ATTEMPTS}…")
        try:
            raw = _call(prompt)
            arr = _parse_candidates_array(raw)
            if not arr:
                logger.info("    No JSON array returned — retrying")
                time.sleep(RETRY_DELAY)
                continue

            # Validate each candidate, keep the ones that clear the hard gates
            # (word count + duplication). Self-scored uniqueness is just a hint
            # — the judge does the final pick.
            valid: list[dict] = []
            below_bar: list[dict] = []
            for raw_item in arr:
                if not isinstance(raw_item, dict):
                    continue
                text = _clean_text(raw_item.get("quote", ""))
                author = (raw_item.get("author") or "").strip()
                if not text or not author:
                    continue

                wc = len(text.split())
                if wc < 3 or wc > max_words + 5:
                    continue
                if _hash(text) in posted_hashes:
                    continue

                virality   = int(raw_item.get("virality",   0) or 0)
                engagement = int(raw_item.get("engagement", 0) or 0)
                uniqueness = int(raw_item.get("uniqueness", 0) or 0)
                freshness  = int(raw_item.get("freshness",  0) or 0)
                score = (virality + engagement + uniqueness + freshness) // 4

                candidate = {
                    "text":       text,
                    "author":     author,
                    "highlight":  _extract_highlight(text),
                    "image_hint": image_hint,
                    "score":      score,
                    "uniqueness": uniqueness,
                    "reason":     raw_item.get("reason", ""),
                    "source":     source_name,
                }

                # Quality floor: uniqueness>=MIN_UNIQUENESS to be a "primary"
                # candidate. Below-bar ones are kept only as fallback if every
                # candidate fails the uniqueness gate.
                if uniqueness >= MIN_UNIQUENESS:
                    valid.append(candidate)
                else:
                    below_bar.append(candidate)

            logger.info(
                f"    Got {len(arr)} candidates, "
                f"{len(valid)} above bar, {len(below_bar)} below"
            )
            for i, c in enumerate(valid, 1):
                logger.info(f"      {i}. \"{c['text'][:90]}\" — {c['author']} (u={c['uniqueness']})")

            if valid:
                pick = _judge_candidates(valid) or valid[0]
                logger.info(f"  ✓ Accepted: \"{pick['text'][:80]}\" — {pick['author']}")
                return pick

            # Track the strongest below-bar candidate across attempts in case
            # we exhaust retries.
            if below_bar:
                best_below = max(below_bar, key=lambda c: c.get("score", 0))
                if fallback is None or best_below["score"] > fallback["score"]:
                    fallback = best_below

        except Exception as exc:
            err = str(exc)
            if "RESOURCE_EXHAUSTED" in err or "429" in err:
                logger.warning(f"  429 / quota exhausted — skipping LLM entirely")
                return None
            logger.warning(f"  Attempt {attempt} error: {exc}")
        time.sleep(RETRY_DELAY)

    if fallback:
        logger.warning(
            f"  Using best below-bar candidate (score {fallback['score']}, "
            f"uniqueness {fallback.get('uniqueness', '?')}) — bar not met"
        )
        return fallback

    return None


# ---------------------------------------------------------------------------
# Universal entry point
# ---------------------------------------------------------------------------

def generate_quote(theme: str, posted_hashes: set,
                   recent_hints: list[str] | None = None) -> dict:
    q = _generate_with_validation(theme, posted_hashes, recent_hints)
    if q:
        return q

    logger.warning("Gemini unavailable or exhausted — using curated fallback pool")
    curated = _pick_curated(theme, posted_hashes)
    if curated:
        return curated

    from src.config import FALLBACK_QUOTES
    pool = list(FALLBACK_QUOTES.get(theme, FALLBACK_QUOTES["wisdom"]))
    random.shuffle(pool)
    for item in pool:
        if _hash(item["text"]) not in posted_hashes:
            item = dict(item)
            item.setdefault("highlight", _extract_highlight(item["text"]))
            item["source"] = "fallback"
            return item
    item = dict(random.choice(pool))
    item.setdefault("highlight", _extract_highlight(item["text"]))
    item["source"] = "fallback"
    return item


# ---------------------------------------------------------------------------
# Handcrafted emergency fallback
# ---------------------------------------------------------------------------

_HANDCRAFTED = [
    {"text": "The wound is the place where the light enters you.", "author": "Rumi"},
    {"text": "Not all those who wander are lost.", "author": "J.R.R. Tolkien"},
    {"text": "We accept the love we think we deserve.", "author": "Stephen Chbosky"},
    {"text": "You can't stop the waves, but you can learn to surf.", "author": "Jon Kabat-Zinn"},
    {"text": "Almost everything will work again if you unplug it for a few minutes — including you.", "author": "Anne Lamott"},
    {"text": "Done is better than perfect.", "author": "Sheryl Sandberg"},
    {"text": "In today's rush we all think too much, seek too much, want too much and forget about the joy of just being.", "author": "Eckhart Tolle"},
]


def _handcrafted_fallback(posted_hashes: set) -> dict:
    pool = [q for q in _HANDCRAFTED if _hash(q["text"]) not in posted_hashes] or _HANDCRAFTED
    item = dict(random.choice(pool))
    item["highlight"] = _extract_highlight(item["text"])
    item["source"] = "fallback"
    return item
